apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-bff
spec:
  selector:
    matchLabels:
      app: nestjs-bff
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-bff
    spec:
      containers:
        - name: nestjs-bff
          image: eseynoa/nestjs-bff
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: '100m' # 0.1 cores
              memory: '128Mi' # 128 MB
            limits:
              cpu: '200m' # 0.2 cores
              memory: '256Mi'
