apiVersion: v1
kind: Service
metadata:
  name: nestjs-bff
spec:
  selector:
    app: nestjs-bff
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32001
  type: LoadBalancer
